### ISSUE TITLE
写于人生操蛋处 | zjuturtle's blog

### ISSUE THREAD

**Issue by zjuturtle** [zjuturtle/zjuturtle.github.io#1]
https://zjuturtle.com/2017/11/10/fuck-the-world/

我有着同龄人没有品质，那就是自知之明和羞耻心。我知道自己是个什么玩意，所以我不想去祸害别人了。 Oslo: Burning the Bridge to Nowhere 又是一年光棍节。除了剁手外，也得记得这个节日最开始面向的是单身狗们而不是马云爸爸啊。

**Comment by zjuturtle** [comment]
评论测试啦～

**Comment by PointerFLY** [comment]
look forward.
